In [5]:
import torch
from torch import nn
from torch.nn import functional as F

x=torch.arange(4)
torch.save(x,"./5_5/x.pt")

In [8]:
x2=torch.load("./5_5/x.pt")
print(x2)

tensor([0, 1, 2, 3])


In [15]:
y=torch.zeros(4)
torch.save([x,y],"./5_5/x-files.txt")
x2,y2=torch.load("./5_5/x-files.txt")
(x2,y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [17]:
mydict={"x":x,"y":y}
torch.save(mydict,"./5_5/mydict.pt")
mydict2=torch.load("./5_5/mydict.pt")
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [25]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    def forward(self,x):
        return self.output(F.relu(self.hidden(x)))

net=MLP()
X=torch.rand(2,20)
Y=net(X)

# 先看看state_dict()返回的字典长什么样
print("模型参数字典的内容:")
state_dict = net.state_dict()
for key, value in state_dict.items():
    print(f"参数名: {key}, 形状: {value.shape}, 类型: {type(value)}")

print("\n详细的参数值:")
print(state_dict)

torch.save(net.state_dict(),"./5_5/mlp.params")

模型参数字典的内容:
参数名: hidden.weight, 形状: torch.Size([256, 20]), 类型: <class 'torch.Tensor'>
参数名: hidden.bias, 形状: torch.Size([256]), 类型: <class 'torch.Tensor'>
参数名: output.weight, 形状: torch.Size([10, 256]), 类型: <class 'torch.Tensor'>
参数名: output.bias, 形状: torch.Size([10]), 类型: <class 'torch.Tensor'>

详细的参数值:
OrderedDict([('hidden.weight', tensor([[-0.0665, -0.0235,  0.2128,  ..., -0.0246,  0.0144,  0.1092],
        [-0.1787,  0.2141, -0.2208,  ..., -0.1779,  0.0731,  0.0078],
        [-0.0290,  0.1873,  0.1175,  ...,  0.0404,  0.1409,  0.0757],
        ...,
        [ 0.0696, -0.0194, -0.1658,  ...,  0.0834, -0.2129, -0.0245],
        [-0.2014, -0.0251, -0.1838,  ...,  0.0527,  0.0730,  0.0860],
        [ 0.1674, -0.0723, -0.0936,  ..., -0.2207,  0.0361, -0.1560]])), ('hidden.bias', tensor([ 0.1981,  0.1310,  0.1727,  0.1153, -0.1772, -0.0142,  0.0517, -0.1963,
        -0.1917,  0.0365,  0.2185,  0.0031,  0.1340,  0.1848, -0.0213, -0.2182,
         0.0727,  0.0779, -0.1884,  0.0929,  0.1811,  

In [ ]:
# state_dict()返回的是一个字典(dict)，包含了模型的所有参数
# 字典的键是参数名，值是对应的张量参数
clone=MLP()
# load_state_dict()方法将保存的参数字典加载到模型中
clone.load_state_dict(torch.load("./5_5/mlp.params"))
# eval()方法将模型设置为评估模式，这会关闭dropout和batch normalization等训练时的特殊行为
clone.eval()
Y_clone=clone(X)
Y_clone==Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])